# import unittest
# # from airflow.dags.src.etl.weather import (
# #     current_weather_condition_formatter,
# #     historical_weather_condition_formatter,
# # )
# from src.custom_types.weather_condition import WeatherConditions, WeatherConditionUnits
# from src.utils.save_load_json import save_json, load_json

# # Run it using `python -m src.tests.test_weather_formatter`


# class WeatherFormatterTestCases(unittest.TestCase):

#     def test_current_weather_condition_formatter(self):

#         raw_data = load_json(filename="src/tests/data/current_weather_response.json")

#         expected_output: WeatherConditions = {
#             "latitude": 48.86,
#             "longitude": 2.3399997,
#             "elevation": 33,
#             "time": 1727107200,
#             "temperature_2m": 15.6,
#             "relative_humidity_2m": 86,
#             "apparent_temperature": 15.6,
#             "is_day": 1,
#             "precipitation": 0,
#             "rain": 0,
#             "showers": 0,
#             "snowfall": 0,
#             "weather_code": 80,
#             "cloud_cover": 100,
#             "pressure_msl": 1007.4,
#             "surface_pressure": 1003.5,
#             "wind_speed_10m": 7.8,
#             "wind_direction_10m": 158,
#             "wind_gusts_10m": 19.4,
#         }

#         weather_conditions: WeatherConditions = current_weather_condition_formatter(
#             raw_data
#         )
#         self.assertEqual(weather_conditions, expected_output)

#     def test_historical_weather_condition_formatter(self):
#         raw_data = load_json(filename="src/tests/data/historical_weather_response.json")

#         expected_output = [
#             {
#                 "latitude": 48.85,
#                 "longitude": 2.3499994,
#                 "elevation": 33.0,
#                 "time": 1726876800,
#                 "temperature_2m": 17.2,
#                 "relative_humidity_2m": 86,
#                 "apparent_temperature": 17.7,
#                 "is_day": 0,
#                 "precipitation": 0.3,
#                 "rain": 0.3,
#                 "showers": 0.0,
#                 "snowfall": 0.0,
#                 "weather_code": 51,
#                 "cloud_cover": 100,
#                 "pressure_msl": 1018.4,
#                 "surface_pressure": 1014.5,
#                 "wind_speed_10m": 3.7,
#                 "wind_direction_10m": 209,
#                 "wind_gusts_10m": 24.8,
#             },
#             {
#                 "latitude": 48.85,
#                 "longitude": 2.3499994,
#                 "elevation": 33.0,
#                 "time": 1726880400,
#                 "temperature_2m": 17.5,
#                 "relative_humidity_2m": 77,
#                 "apparent_temperature": 18.1,
#                 "is_day": 0,
#                 "precipitation": 0.2,
#                 "rain": 0.2,
#                 "showers": 0.0,
#                 "snowfall": 0.0,
#                 "weather_code": 51,
#                 "cloud_cover": 99,
#                 "pressure_msl": 1018.6,
#                 "surface_pressure": 1014.7,
#                 "wind_speed_10m": 0.7,
#                 "wind_direction_10m": 360,
#                 "wind_gusts_10m": 27.7,
#             },
#             {
#                 "latitude": 48.85,
#                 "longitude": 2.3499994,
#                 "elevation": 33.0,
#                 "time": 1726884000,
#                 "temperature_2m": 17.1,
#                 "relative_humidity_2m": 83,
#                 "apparent_temperature": 17.2,
#                 "is_day": 0,
#                 "precipitation": 0.0,
#                 "rain": 0.0,
#                 "showers": 0.0,
#                 "snowfall": 0.0,
#                 "weather_code": 3,
#                 "cloud_cover": 100,
#                 "pressure_msl": 1018.6,
#                 "surface_pressure": 1014.7,
#                 "wind_speed_10m": 5.2,
#                 "wind_direction_10m": 115,
#                 "wind_gusts_10m": 22.7,
#             },
#             {
#                 "latitude": 48.85,
#                 "longitude": 2.3499994,
#                 "elevation": 33.0,
#                 "time": 1726887600,
#                 "temperature_2m": 17.5,
#                 "relative_humidity_2m": 80,
#                 "apparent_temperature": 18.1,
#                 "is_day": 0,
#                 "precipitation": 0.0,
#                 "rain": 0.0,
#                 "showers": 0.0,
#                 "snowfall": 0.0,
#                 "weather_code": 3,
#                 "cloud_cover": 100,
#                 "pressure_msl": 1017.5,
#                 "surface_pressure": 1013.6,
#                 "wind_speed_10m": 3.3,
#                 "wind_direction_10m": 103,
#                 "wind_gusts_10m": 16.6,
#             },
#             {
#                 "latitude": 48.85,
#                 "longitude": 2.3499994,
#                 "elevation": 33.0,
#                 "time": 1726891200,
#                 "temperature_2m": 17.0,
#                 "relative_humidity_2m": 81,
#                 "apparent_temperature": 18.0,
#                 "is_day": 0,
#                 "precipitation": 0.0,
#                 "rain": 0.0,
#                 "showers": 0.0,
#                 "snowfall": 0.0,
#                 "weather_code": 3,
#                 "cloud_cover": 100,
#                 "pressure_msl": 1018.1,
#                 "surface_pressure": 1014.2,
#                 "wind_speed_10m": 7.6,
#                 "wind_direction_10m": 109,
#                 "wind_gusts_10m": 17.3,
#             },
#             {
#                 "latitude": 48.85,
#                 "longitude": 2.3499994,
#                 "elevation": 33.0,
#                 "time": 1726894800,
#                 "temperature_2m": 16.6,
#                 "relative_humidity_2m": 87,
#                 "apparent_temperature": 16.8,
#                 "is_day": 0,
#                 "precipitation": 0.0,
#                 "rain": 0.0,
#                 "showers": 0.0,
#                 "snowfall": 0.0,
#                 "weather_code": 3,
#                 "cloud_cover": 100,
#                 "pressure_msl": 1018.0,
#                 "surface_pressure": 1014.0,
#                 "wind_speed_10m": 5.0,
#                 "wind_direction_10m": 111,
#                 "wind_gusts_10m": 15.5,
#             },
#             {
#                 "latitude": 48.85,
#                 "longitude": 2.3499994,
#                 "elevation": 33.0,
#                 "time": 1726898400,
#                 "temperature_2m": 16.8,
#                 "relative_humidity_2m": 84,
#                 "apparent_temperature": 17.1,
#                 "is_day": 1,
#                 "precipitation": 0.0,
#                 "rain": 0.0,
#                 "showers": 0.0,
#                 "snowfall": 0.0,
#                 "weather_code": 3,
#                 "cloud_cover": 100,
#                 "pressure_msl": 1017.8,
#                 "surface_pressure": 1013.8,
#                 "wind_speed_10m": 4.0,
#                 "wind_direction_10m": 117,
#                 "wind_gusts_10m": 16.2,
#             },
#             {
#                 "latitude": 48.85,
#                 "longitude": 2.3499994,
#                 "elevation": 33.0,
#                 "time": 1726902000,
#                 "temperature_2m": 17.4,
#                 "relative_humidity_2m": 80,
#                 "apparent_temperature": 17.0,
#                 "is_day": 1,
#                 "precipitation": 0.0,
#                 "rain": 0.0,
#                 "showers": 0.0,
#                 "snowfall": 0.0,
#                 "weather_code": 0,
#                 "cloud_cover": 8,
#                 "pressure_msl": 1017.9,
#                 "surface_pressure": 1013.9,
#                 "wind_speed_10m": 7.1,
#                 "wind_direction_10m": 131,
#                 "wind_gusts_10m": 15.5,
#             },
#             {
#                 "latitude": 48.85,
#                 "longitude": 2.3499994,
#                 "elevation": 33.0,
#                 "time": 1726905600,
#                 "temperature_2m": 17.9,
#                 "relative_humidity_2m": 78,
#                 "apparent_temperature": 17.5,
#                 "is_day": 1,
#                 "precipitation": 0.0,
#                 "rain": 0.0,
#                 "showers": 0.0,
#                 "snowfall": 0.0,
#                 "weather_code": 3,
#                 "cloud_cover": 99,
#                 "pressure_msl": 1017.8,
#                 "surface_pressure": 1013.9,
#                 "wind_speed_10m": 7.7,
#                 "wind_direction_10m": 131,
#                 "wind_gusts_10m": 21.2,
#             },
#             {
#                 "latitude": 48.85,
#                 "longitude": 2.3499994,
#                 "elevation": 33.0,
#                 "time": 1726909200,
#                 "temperature_2m": 19.1,
#                 "relative_humidity_2m": 76,
#                 "apparent_temperature": 19.2,
#                 "is_day": 1,
#                 "precipitation": 0.0,
#                 "rain": 0.0,
#                 "showers": 0.0,
#                 "snowfall": 0.0,
#                 "weather_code": 0,
#                 "cloud_cover": 12,
#                 "pressure_msl": 1018.0,
#                 "surface_pressure": 1014.1,
#                 "wind_speed_10m": 8.9,
#                 "wind_direction_10m": 133,
#                 "wind_gusts_10m": 27.0,
#             },
#             {
#                 "latitude": 48.85,
#                 "longitude": 2.3499994,
#                 "elevation": 33.0,
#                 "time": 1726912800,
#                 "temperature_2m": 20.9,
#                 "relative_humidity_2m": 69,
#                 "apparent_temperature": 21.1,
#                 "is_day": 1,
#                 "precipitation": 0.0,
#                 "rain": 0.0,
#                 "showers": 0.0,
#                 "snowfall": 0.0,
#                 "weather_code": 0,
#                 "cloud_cover": 0,
#                 "pressure_msl": 1017.4,
#                 "surface_pressure": 1013.5,
#                 "wind_speed_10m": 13.1,
#                 "wind_direction_10m": 143,
#                 "wind_gusts_10m": 23.0,
#             },
#             {
#                 "latitude": 48.85,
#                 "longitude": 2.3499994,
#                 "elevation": 33.0,
#                 "time": 1726916400,
#                 "temperature_2m": 22.1,
#                 "relative_humidity_2m": 64,
#                 "apparent_temperature": 22.1,
#                 "is_day": 1,
#                 "precipitation": 0.0,
#                 "rain": 0.0,
#                 "showers": 0.0,
#                 "snowfall": 0.0,
#                 "weather_code": 2,
#                 "cloud_cover": 79,
#                 "pressure_msl": 1017.1,
#                 "surface_pressure": 1013.2,
#                 "wind_speed_10m": 12.6,
#                 "wind_direction_10m": 143,
#                 "wind_gusts_10m": 26.6,
#             },
#             {
#                 "latitude": 48.85,
#                 "longitude": 2.3499994,
#                 "elevation": 33.0,
#                 "time": 1726920000,
#                 "temperature_2m": 22.9,
#                 "relative_humidity_2m": 60,
#                 "apparent_temperature": 22.9,
#                 "is_day": 1,
#                 "precipitation": 0.0,
#                 "rain": 0.0,
#                 "showers": 0.0,
#                 "snowfall": 0.0,
#                 "weather_code": 3,
#                 "cloud_cover": 95,
#                 "pressure_msl": 1016.5,
#                 "surface_pressure": 1012.6,
#                 "wind_speed_10m": 14.1,
#                 "wind_direction_10m": 148,
#                 "wind_gusts_10m": 30.6,
#             },
#             {
#                 "latitude": 48.85,
#                 "longitude": 2.3499994,
#                 "elevation": 33.0,
#                 "time": 1726923600,
#                 "temperature_2m": 24.0,
#                 "relative_humidity_2m": 51,
#                 "apparent_temperature": 23.2,
#                 "is_day": 1,
#                 "precipitation": 0.0,
#                 "rain": 0.0,
#                 "showers": 0.0,
#                 "snowfall": 0.0,
#                 "weather_code": 3,
#                 "cloud_cover": 100,
#                 "pressure_msl": 1015.5,
#                 "surface_pressure": 1011.7,
#                 "wind_speed_10m": 13.8,
#                 "wind_direction_10m": 141,
#                 "wind_gusts_10m": 30.2,
#             },
#             {
#                 "latitude": 48.85,
#                 "longitude": 2.3499994,
#                 "elevation": 33.0,
#                 "time": 1726927200,
#                 "temperature_2m": 24.2,
#                 "relative_humidity_2m": 53,
#                 "apparent_temperature": 23.6,
#                 "is_day": 1,
#                 "precipitation": 0.0,
#                 "rain": 0.0,
#                 "showers": 0.0,
#                 "snowfall": 0.0,
#                 "weather_code": 3,
#                 "cloud_cover": 100,
#                 "pressure_msl": 1015.8,
#                 "surface_pressure": 1012.0,
#                 "wind_speed_10m": 13.2,
#                 "wind_direction_10m": 125,
#                 "wind_gusts_10m": 28.8,
#             },
#             {
#                 "latitude": 48.85,
#                 "longitude": 2.3499994,
#                 "elevation": 33.0,
#                 "time": 1726930800,
#                 "temperature_2m": 24.1,
#                 "relative_humidity_2m": 55,
#                 "apparent_temperature": 23.9,
#                 "is_day": 1,
#                 "precipitation": 1.8,
#                 "rain": 1.8,
#                 "showers": 0.0,
#                 "snowfall": 0.0,
#                 "weather_code": 61,
#                 "cloud_cover": 100,
#                 "pressure_msl": 1015.4,
#                 "surface_pressure": 1011.6,
#                 "wind_speed_10m": 11.4,
#                 "wind_direction_10m": 125,
#                 "wind_gusts_10m": 30.2,
#             },
#             {
#                 "latitude": 48.85,
#                 "longitude": 2.3499994,
#                 "elevation": 33.0,
#                 "time": 1726934400,
#                 "temperature_2m": 22.4,
#                 "relative_humidity_2m": 69,
#                 "apparent_temperature": 23.4,
#                 "is_day": 1,
#                 "precipitation": 0.0,
#                 "rain": 0.0,
#                 "showers": 0.0,
#                 "snowfall": 0.0,
#                 "weather_code": 3,
#                 "cloud_cover": 100,
#                 "pressure_msl": 1015.3,
#                 "surface_pressure": 1011.5,
#                 "wind_speed_10m": 6.6,
#                 "wind_direction_10m": 103,
#                 "wind_gusts_10m": 25.9,
#             },
#             {
#                 "latitude": 48.85,
#                 "longitude": 2.3499994,
#                 "elevation": 33.0,
#                 "time": 1726938000,
#                 "temperature_2m": 21.4,
#                 "relative_humidity_2m": 62,
#                 "apparent_temperature": 22.1,
#                 "is_day": 1,
#                 "precipitation": 0.0,
#                 "rain": 0.0,
#                 "showers": 0.0,
#                 "snowfall": 0.0,
#                 "weather_code": 3,
#                 "cloud_cover": 100,
#                 "pressure_msl": 1014.9,
#                 "surface_pressure": 1011.0,
#                 "wind_speed_10m": 7.6,
#                 "wind_direction_10m": 95,
#                 "wind_gusts_10m": 35.3,
#             },
#             {
#                 "latitude": 48.85,
#                 "longitude": 2.3499994,
#                 "elevation": 33.0,
#                 "time": 1726941600,
#                 "temperature_2m": 21.1,
#                 "relative_humidity_2m": 68,
#                 "apparent_temperature": 21.2,
#                 "is_day": 0,
#                 "precipitation": 0.0,
#                 "rain": 0.0,
#                 "showers": 0.0,
#                 "snowfall": 0.0,
#                 "weather_code": 3,
#                 "cloud_cover": 100,
#                 "pressure_msl": 1014.9,
#                 "surface_pressure": 1011.0,
#                 "wind_speed_10m": 7.0,
#                 "wind_direction_10m": 111,
#                 "wind_gusts_10m": 21.6,
#             },
#             {
#                 "latitude": 48.85,
#                 "longitude": 2.3499994,
#                 "elevation": 33.0,
#                 "time": 1726945200,
#                 "temperature_2m": 20.0,
#                 "relative_humidity_2m": 72,
#                 "apparent_temperature": 21.1,
#                 "is_day": 0,
#                 "precipitation": 0.0,
#                 "rain": 0.0,
#                 "showers": 0.0,
#                 "snowfall": 0.0,
#                 "weather_code": 63,
#                 "cloud_cover": 100,
#                 "pressure_msl": 1015.2,
#                 "surface_pressure": 1011.3,
#                 "wind_speed_10m": 6.5,
#                 "wind_direction_10m": 124,
#                 "wind_gusts_10m": 23.0,
#             },
#             {
#                 "latitude": 48.85,
#                 "longitude": 2.3499994,
#                 "elevation": 33.0,
#                 "time": 1726948800,
#                 "temperature_2m": 19.8,
#                 "relative_humidity_2m": 72,
#                 "apparent_temperature": 22.0,
#                 "is_day": 0,
#                 "precipitation": 0.0,
#                 "rain": 0.0,
#                 "showers": 0.0,
#                 "snowfall": 0.0,
#                 "weather_code": 3,
#                 "cloud_cover": 100,
#                 "pressure_msl": 1014.9,
#                 "surface_pressure": 1011.0,
#                 "wind_speed_10m": 7.4,
#                 "wind_direction_10m": 133,
#                 "wind_gusts_10m": 13.7,
#             },
#             {
#                 "latitude": 48.85,
#                 "longitude": 2.3499994,
#                 "elevation": 33.0,
#                 "time": 1726952400,
#                 "temperature_2m": 19.5,
#                 "relative_humidity_2m": 77,
#                 "apparent_temperature": 21.3,
#                 "is_day": 0,
#                 "precipitation": 0.0,
#                 "rain": 0.0,
#                 "showers": 0.0,
#                 "snowfall": 0.0,
#                 "weather_code": 3,
#                 "cloud_cover": 100,
#                 "pressure_msl": 1015.1,
#                 "surface_pressure": 1011.2,
#                 "wind_speed_10m": 8.1,
#                 "wind_direction_10m": 135,
#                 "wind_gusts_10m": 16.9,
#             },
#             {
#                 "latitude": 48.85,
#                 "longitude": 2.3499994,
#                 "elevation": 33.0,
#                 "time": 1726956000,
#                 "temperature_2m": 20.5,
#                 "relative_humidity_2m": 71,
#                 "apparent_temperature": 20.9,
#                 "is_day": 0,
#                 "precipitation": 0.0,
#                 "rain": 0.0,
#                 "showers": 0.0,
#                 "snowfall": 0.0,
#                 "weather_code": 3,
#                 "cloud_cover": 100,
#                 "pressure_msl": 1014.6,
#                 "surface_pressure": 1010.7,
#                 "wind_speed_10m": 8.5,
#                 "wind_direction_10m": 118,
#                 "wind_gusts_10m": 17.3,
#             },
#             {
#                 "latitude": 48.85,
#                 "longitude": 2.3499994,
#                 "elevation": 33.0,
#                 "time": 1726959600,
#                 "temperature_2m": 19.6,
#                 "relative_humidity_2m": 77,
#                 "apparent_temperature": 20.6,
#                 "is_day": 0,
#                 "precipitation": 0.0,
#                 "rain": 0.0,
#                 "showers": 0.0,
#                 "snowfall": 0.0,
#                 "weather_code": 3,
#                 "cloud_cover": 100,
#                 "pressure_msl": 1014.8,
#                 "surface_pressure": 1010.9,
#                 "wind_speed_10m": 8.8,
#                 "wind_direction_10m": 199,
#                 "wind_gusts_10m": 18.4,
#             },
#             {
#                 "latitude": 48.85,
#                 "longitude": 2.3499994,
#                 "elevation": 33.0,
#                 "time": 1726963200,
#                 "temperature_2m": 18.7,
#                 "relative_humidity_2m": 86,
#                 "apparent_temperature": 20.9,
#                 "is_day": 0,
#                 "precipitation": 0.3,
#                 "rain": 0.3,
#                 "showers": 0.0,
#                 "snowfall": 0.0,
#                 "weather_code": 51,
#                 "cloud_cover": 100,
#                 "pressure_msl": 1014.7,
#                 "surface_pressure": 1010.8,
#                 "wind_speed_10m": 5.0,
#                 "wind_direction_10m": 150,
#                 "wind_gusts_10m": 23.0,
#             },
#             {
#                 "latitude": 48.85,
#                 "longitude": 2.3499994,
#                 "elevation": 33.0,
#                 "time": 1726966800,
#                 "temperature_2m": 18.6,
#                 "relative_humidity_2m": 85,
#                 "apparent_temperature": 19.7,
#                 "is_day": 0,
#                 "precipitation": 0.0,
#                 "rain": 0.0,
#                 "showers": 0.0,
#                 "snowfall": 0.0,
#                 "weather_code": 3,
#                 "cloud_cover": 100,
#                 "pressure_msl": 1014.5,
#                 "surface_pressure": 1010.6,
#                 "wind_speed_10m": 3.6,
#                 "wind_direction_10m": 135,
#                 "wind_gusts_10m": 14.8,
#             },
#             {
#                 "latitude": 48.85,
#                 "longitude": 2.3499994,
#                 "elevation": 33.0,
#                 "time": 1726970400,
#                 "temperature_2m": 18.5,
#                 "relative_humidity_2m": 86,
#                 "apparent_temperature": 19.6,
#                 "is_day": 0,
#                 "precipitation": 0.8,
#                 "rain": 0.8,
#                 "showers": 0.0,
#                 "snowfall": 0.0,
#                 "weather_code": 53,
#                 "cloud_cover": 100,
#                 "pressure_msl": 1014.4,
#                 "surface_pressure": 1010.5,
#                 "wind_speed_10m": 7.0,
#                 "wind_direction_10m": 168,
#                 "wind_gusts_10m": 14.4,
#             },
#             {
#                 "latitude": 48.85,
#                 "longitude": 2.3499994,
#                 "elevation": 33.0,
#                 "time": 1726974000,
#                 "temperature_2m": 18.1,
#                 "relative_humidity_2m": 86,
#                 "apparent_temperature": 19.1,
#                 "is_day": 0,
#                 "precipitation": 0.5,
#                 "rain": 0.5,
#                 "showers": 0.0,
#                 "snowfall": 0.0,
#                 "weather_code": 53,
#                 "cloud_cover": 100,
#                 "pressure_msl": 1013.8,
#                 "surface_pressure": 1009.9,
#                 "wind_speed_10m": 6.0,
#                 "wind_direction_10m": 163,
#                 "wind_gusts_10m": 13.0,
#             },
#             {
#                 "latitude": 48.85,
#                 "longitude": 2.3499994,
#                 "elevation": 33.0,
#                 "time": 1726977600,
#                 "temperature_2m": 17.6,
#                 "relative_humidity_2m": 89,
#                 "apparent_temperature": 19.0,
#                 "is_day": 0,
#                 "precipitation": 0.1,
#                 "rain": 0.1,
#                 "showers": 0.0,
#                 "snowfall": 0.0,
#                 "weather_code": 51,
#                 "cloud_cover": 100,
#                 "pressure_msl": 1013.4,
#                 "surface_pressure": 1009.5,
#                 "wind_speed_10m": 6.4,
#                 "wind_direction_10m": 133,
#                 "wind_gusts_10m": 14.0,
#             },
#             {
#                 "latitude": 48.85,
#                 "longitude": 2.3499994,
#                 "elevation": 33.0,
#                 "time": 1726981200,
#                 "temperature_2m": 17.9,
#                 "relative_humidity_2m": 88,
#                 "apparent_temperature": 19.1,
#                 "is_day": 0,
#                 "precipitation": 0.0,
#                 "rain": 0.0,
#                 "showers": 0.0,
#                 "snowfall": 0.0,
#                 "weather_code": 53,
#                 "cloud_cover": 100,
#                 "pressure_msl": 1013.4,
#                 "surface_pressure": 1009.5,
#                 "wind_speed_10m": 3.6,
#                 "wind_direction_10m": 135,
#                 "wind_gusts_10m": 13.3,
#             },
#             {
#                 "latitude": 48.85,
#                 "longitude": 2.3499994,
#                 "elevation": 33.0,
#                 "time": 1726984800,
#                 "temperature_2m": 18.3,
#                 "relative_humidity_2m": 84,
#                 "apparent_temperature": 19.4,
#                 "is_day": 1,
#                 "precipitation": 0.0,
#                 "rain": 0.0,
#                 "showers": 0.0,
#                 "snowfall": 0.0,
#                 "weather_code": 3,
#                 "cloud_cover": 100,
#                 "pressure_msl": 1013.7,
#                 "surface_pressure": 1009.8,
#                 "wind_speed_10m": 5.8,
#                 "wind_direction_10m": 120,
#                 "wind_gusts_10m": 13.0,
#             },
#             {
#                 "latitude": 48.85,
#                 "longitude": 2.3499994,
#                 "elevation": 33.0,
#                 "time": 1726988400,
#                 "temperature_2m": 18.0,
#                 "relative_humidity_2m": 85,
#                 "apparent_temperature": 19.0,
#                 "is_day": 1,
#                 "precipitation": 0.0,
#                 "rain": 0.0,
#                 "showers": 0.0,
#                 "snowfall": 0.0,
#                 "weather_code": 3,
#                 "cloud_cover": 100,
#                 "pressure_msl": 1013.1,
#                 "surface_pressure": 1009.2,
#                 "wind_speed_10m": 5.4,
#                 "wind_direction_10m": 138,
#                 "wind_gusts_10m": 16.2,
#             },
#             {
#                 "latitude": 48.85,
#                 "longitude": 2.3499994,
#                 "elevation": 33.0,
#                 "time": 1726992000,
#                 "temperature_2m": 18.6,
#                 "relative_humidity_2m": 85,
#                 "apparent_temperature": 20.4,
#                 "is_day": 1,
#                 "precipitation": 0.0,
#                 "rain": 0.0,
#                 "showers": 0.0,
#                 "snowfall": 0.0,
#                 "weather_code": 3,
#                 "cloud_cover": 100,
#                 "pressure_msl": 1013.4,
#                 "surface_pressure": 1009.5,
#                 "wind_speed_10m": 6.6,
#                 "wind_direction_10m": 151,
#                 "wind_gusts_10m": 15.5,
#             },
#             {
#                 "latitude": 48.85,
#                 "longitude": 2.3499994,
#                 "elevation": 33.0,
#                 "time": 1726995600,
#                 "temperature_2m": 18.1,
#                 "relative_humidity_2m": 87,
#                 "apparent_temperature": 20.7,
#                 "is_day": 1,
#                 "precipitation": 0.3,
#                 "rain": 0.3,
#                 "showers": 0.0,
#                 "snowfall": 0.0,
#                 "weather_code": 51,
#                 "cloud_cover": 100,
#                 "pressure_msl": 1013.6,
#                 "surface_pressure": 1009.7,
#                 "wind_speed_10m": 7.6,
#                 "wind_direction_10m": 161,
#                 "wind_gusts_10m": 16.9,
#             },
#             {
#                 "latitude": 48.85,
#                 "longitude": 2.3499994,
#                 "elevation": 33.0,
#                 "time": 1726999200,
#                 "temperature_2m": 19.8,
#                 "relative_humidity_2m": 81,
#                 "apparent_temperature": 21.1,
#                 "is_day": 1,
#                 "precipitation": 0.1,
#                 "rain": 0.1,
#                 "showers": 0.0,
#                 "snowfall": 0.0,
#                 "weather_code": 51,
#                 "cloud_cover": 100,
#                 "pressure_msl": 1013.4,
#                 "surface_pressure": 1009.5,
#                 "wind_speed_10m": 8.7,
#                 "wind_direction_10m": 175,
#                 "wind_gusts_10m": 18.0,
#             },
#             {
#                 "latitude": 48.85,
#                 "longitude": 2.3499994,
#                 "elevation": 33.0,
#                 "time": 1727002800,
#                 "temperature_2m": 19.6,
#                 "relative_humidity_2m": 80,
#                 "apparent_temperature": 21.1,
#                 "is_day": 1,
#                 "precipitation": 0.0,
#                 "rain": 0.0,
#                 "showers": 0.0,
#                 "snowfall": 0.0,
#                 "weather_code": 3,
#                 "cloud_cover": 100,
#                 "pressure_msl": 1012.9,
#                 "surface_pressure": 1009.0,
#                 "wind_speed_10m": 9.2,
#                 "wind_direction_10m": 206,
#                 "wind_gusts_10m": 20.5,
#             },
#             {
#                 "latitude": 48.85,
#                 "longitude": 2.3499994,
#                 "elevation": 33.0,
#                 "time": 1727006400,
#                 "temperature_2m": 20.6,
#                 "relative_humidity_2m": 75,
#                 "apparent_temperature": 21.3,
#                 "is_day": 1,
#                 "precipitation": 0.0,
#                 "rain": 0.0,
#                 "showers": 0.0,
#                 "snowfall": 0.0,
#                 "weather_code": 3,
#                 "cloud_cover": 100,
#                 "pressure_msl": 1012.8,
#                 "surface_pressure": 1008.9,
#                 "wind_speed_10m": 9.5,
#                 "wind_direction_10m": 189,
#                 "wind_gusts_10m": 22.3,
#             },
#             {
#                 "latitude": 48.85,
#                 "longitude": 2.3499994,
#                 "elevation": 33.0,
#                 "time": 1727010000,
#                 "temperature_2m": 21.2,
#                 "relative_humidity_2m": 69,
#                 "apparent_temperature": 20.9,
#                 "is_day": 1,
#                 "precipitation": 0.0,
#                 "rain": 0.0,
#                 "showers": 0.0,
#                 "snowfall": 0.0,
#                 "weather_code": 3,
#                 "cloud_cover": 100,
#                 "pressure_msl": 1011.9,
#                 "surface_pressure": 1008.0,
#                 "wind_speed_10m": 10.1,
#                 "wind_direction_10m": 180,
#                 "wind_gusts_10m": 25.9,
#             },
#             {
#                 "latitude": 48.85,
#                 "longitude": 2.3499994,
#                 "elevation": 33.0,
#                 "time": 1727013600,
#                 "temperature_2m": 19.7,
#                 "relative_humidity_2m": 80,
#                 "apparent_temperature": 21.2,
#                 "is_day": 1,
#                 "precipitation": 0.0,
#                 "rain": 0.0,
#                 "showers": 0.0,
#                 "snowfall": 0.0,
#                 "weather_code": 3,
#                 "cloud_cover": 100,
#                 "pressure_msl": 1011.0,
#                 "surface_pressure": 1007.1,
#                 "wind_speed_10m": 11.4,
#                 "wind_direction_10m": 162,
#                 "wind_gusts_10m": 25.6,
#             },
#             {
#                 "latitude": 48.85,
#                 "longitude": 2.3499994,
#                 "elevation": 33.0,
#                 "time": 1727017200,
#                 "temperature_2m": 20.9,
#                 "relative_humidity_2m": 68,
#                 "apparent_temperature": 20.9,
#                 "is_day": 1,
#                 "precipitation": 0.0,
#                 "rain": 0.0,
#                 "showers": 0.0,
#                 "snowfall": 0.0,
#                 "weather_code": 3,
#                 "cloud_cover": 100,
#                 "pressure_msl": 1011.1,
#                 "surface_pressure": 1007.2,
#                 "wind_speed_10m": 11.1,
#                 "wind_direction_10m": 167,
#                 "wind_gusts_10m": 21.6,
#             },
#             {
#                 "latitude": 48.85,
#                 "longitude": 2.3499994,
#                 "elevation": 33.0,
#                 "time": 1727020800,
#                 "temperature_2m": 19.8,
#                 "relative_humidity_2m": 77,
#                 "apparent_temperature": 18.8,
#                 "is_day": 1,
#                 "precipitation": 0.3,
#                 "rain": 0.3,
#                 "showers": 0.0,
#                 "snowfall": 0.0,
#                 "weather_code": 51,
#                 "cloud_cover": 100,
#                 "pressure_msl": 1011.2,
#                 "surface_pressure": 1007.3,
#                 "wind_speed_10m": 14.7,
#                 "wind_direction_10m": 158,
#                 "wind_gusts_10m": 28.1,
#             },
#             {
#                 "latitude": 48.85,
#                 "longitude": 2.3499994,
#                 "elevation": 33.0,
#                 "time": 1727024400,
#                 "temperature_2m": 18.6,
#                 "relative_humidity_2m": 83,
#                 "apparent_temperature": 18.4,
#                 "is_day": 1,
#                 "precipitation": 0.4,
#                 "rain": 0.4,
#                 "showers": 0.0,
#                 "snowfall": 0.0,
#                 "weather_code": 51,
#                 "cloud_cover": 100,
#                 "pressure_msl": 1011.0,
#                 "surface_pressure": 1007.1,
#                 "wind_speed_10m": 11.9,
#                 "wind_direction_10m": 151,
#                 "wind_gusts_10m": 26.6,
#             },
#             {
#                 "latitude": 48.85,
#                 "longitude": 2.3499994,
#                 "elevation": 33.0,
#                 "time": 1727028000,
#                 "temperature_2m": 17.7,
#                 "relative_humidity_2m": 88,
#                 "apparent_temperature": 18.2,
#                 "is_day": 0,
#                 "precipitation": 0.4,
#                 "rain": 0.4,
#                 "showers": 0.0,
#                 "snowfall": 0.0,
#                 "weather_code": 51,
#                 "cloud_cover": 100,
#                 "pressure_msl": 1010.7,
#                 "surface_pressure": 1006.8,
#                 "wind_speed_10m": 9.2,
#                 "wind_direction_10m": 154,
#                 "wind_gusts_10m": 19.4,
#             },
#             {
#                 "latitude": 48.85,
#                 "longitude": 2.3499994,
#                 "elevation": 33.0,
#                 "time": 1727031600,
#                 "temperature_2m": 17.4,
#                 "relative_humidity_2m": 91,
#                 "apparent_temperature": 18.5,
#                 "is_day": 0,
#                 "precipitation": 1.5,
#                 "rain": 1.5,
#                 "showers": 0.0,
#                 "snowfall": 0.0,
#                 "weather_code": 61,
#                 "cloud_cover": 100,
#                 "pressure_msl": 1010.4,
#                 "surface_pressure": 1006.5,
#                 "wind_speed_10m": 7.0,
#                 "wind_direction_10m": 168,
#                 "wind_gusts_10m": 17.3,
#             },
#             {
#                 "latitude": 48.85,
#                 "longitude": 2.3499994,
#                 "elevation": 33.0,
#                 "time": 1727035200,
#                 "temperature_2m": 17.4,
#                 "relative_humidity_2m": 92,
#                 "apparent_temperature": 18.1,
#                 "is_day": 0,
#                 "precipitation": 4.2,
#                 "rain": 4.2,
#                 "showers": 0.0,
#                 "snowfall": 0.0,
#                 "weather_code": 63,
#                 "cloud_cover": 100,
#                 "pressure_msl": 1010.6,
#                 "surface_pressure": 1006.7,
#                 "wind_speed_10m": 7.7,
#                 "wind_direction_10m": 233,
#                 "wind_gusts_10m": 17.6,
#             },
#             {
#                 "latitude": 48.85,
#                 "longitude": 2.3499994,
#                 "elevation": 33.0,
#                 "time": 1727038800,
#                 "temperature_2m": 17.2,
#                 "relative_humidity_2m": 86,
#                 "apparent_temperature": 17.8,
#                 "is_day": 0,
#                 "precipitation": 0.8,
#                 "rain": 0.8,
#                 "showers": 0.0,
#                 "snowfall": 0.0,
#                 "weather_code": 53,
#                 "cloud_cover": 100,
#                 "pressure_msl": 1010.7,
#                 "surface_pressure": 1006.8,
#                 "wind_speed_10m": 8.9,
#                 "wind_direction_10m": 223,
#                 "wind_gusts_10m": 20.5,
#             },
#             {
#                 "latitude": 48.85,
#                 "longitude": 2.3499994,
#                 "elevation": 33.0,
#                 "time": 1727042400,
#                 "temperature_2m": 16.8,
#                 "relative_humidity_2m": 88,
#                 "apparent_temperature": 16.8,
#                 "is_day": 0,
#                 "precipitation": 0.0,
#                 "rain": 0.0,
#                 "showers": 0.0,
#                 "snowfall": 0.0,
#                 "weather_code": 3,
#                 "cloud_cover": 100,
#                 "pressure_msl": 1010.5,
#                 "surface_pressure": 1006.6,
#                 "wind_speed_10m": 6.8,
#                 "wind_direction_10m": 212,
#                 "wind_gusts_10m": 16.9,
#             },
#             {
#                 "latitude": 48.85,
#                 "longitude": 2.3499994,
#                 "elevation": 33.0,
#                 "time": 1727046000,
#                 "temperature_2m": 16.6,
#                 "relative_humidity_2m": 88,
#                 "apparent_temperature": 16.8,
#                 "is_day": 0,
#                 "precipitation": 0.1,
#                 "rain": 0.1,
#                 "showers": 0.0,
#                 "snowfall": 0.0,
#                 "weather_code": 51,
#                 "cloud_cover": 100,
#                 "pressure_msl": 1010.7,
#                 "surface_pressure": 1006.8,
#                 "wind_speed_10m": 7.8,
#                 "wind_direction_10m": 202,
#                 "wind_gusts_10m": 17.3,
#             },
#             {
#                 "latitude": 48.85,
#                 "longitude": 2.3499994,
#                 "elevation": 33.0,
#                 "time": 1727049600,
#                 "temperature_2m": 16.6,
#                 "relative_humidity_2m": 89,
#                 "apparent_temperature": 17.0,
#                 "is_day": 0,
#                 "precipitation": 0.0,
#                 "rain": 0.0,
#                 "showers": 0.0,
#                 "snowfall": 0.0,
#                 "weather_code": 3,
#                 "cloud_cover": 100,
#                 "pressure_msl": 1010.3,
#                 "surface_pressure": 1006.4,
#                 "wind_speed_10m": 5.4,
#                 "wind_direction_10m": 184,
#                 "wind_gusts_10m": 18.0,
#             },
#             {
#                 "latitude": 48.85,
#                 "longitude": 2.3499994,
#                 "elevation": 33.0,
#                 "time": 1727053200,
#                 "temperature_2m": 16.2,
#                 "relative_humidity_2m": 90,
#                 "apparent_temperature": 16.9,
#                 "is_day": 0,
#                 "precipitation": 0.0,
#                 "rain": 0.0,
#                 "showers": 0.0,
#                 "snowfall": 0.0,
#                 "weather_code": 3,
#                 "cloud_cover": 87,
#                 "pressure_msl": 1009.9,
#                 "surface_pressure": 1006.0,
#                 "wind_speed_10m": 7.6,
#                 "wind_direction_10m": 175,
#                 "wind_gusts_10m": 17.3,
#             },
#             {
#                 "latitude": 48.85,
#                 "longitude": 2.3499994,
#                 "elevation": 33.0,
#                 "time": 1727056800,
#                 "temperature_2m": 16.6,
#                 "relative_humidity_2m": 89,
#                 "apparent_temperature": 16.3,
#                 "is_day": 0,
#                 "precipitation": 0.0,
#                 "rain": 0.0,
#                 "showers": 0.0,
#                 "snowfall": 0.0,
#                 "weather_code": 3,
#                 "cloud_cover": 95,
#                 "pressure_msl": 1009.9,
#                 "surface_pressure": 1006.0,
#                 "wind_speed_10m": 11.2,
#                 "wind_direction_10m": 195,
#                 "wind_gusts_10m": 26.3,
#             },
#             {
#                 "latitude": 48.85,
#                 "longitude": 2.3499994,
#                 "elevation": 33.0,
#                 "time": 1727060400,
#                 "temperature_2m": 16.5,
#                 "relative_humidity_2m": 88,
#                 "apparent_temperature": 16.5,
#                 "is_day": 0,
#                 "precipitation": 0.0,
#                 "rain": 0.0,
#                 "showers": 0.0,
#                 "snowfall": 0.0,
#                 "weather_code": 3,
#                 "cloud_cover": 100,
#                 "pressure_msl": 1009.5,
#                 "surface_pressure": 1005.6,
#                 "wind_speed_10m": 10.5,
#                 "wind_direction_10m": 218,
#                 "wind_gusts_10m": 26.6,
#             },
#             {
#                 "latitude": 48.85,
#                 "longitude": 2.3499994,
#                 "elevation": 33.0,
#                 "time": 1727064000,
#                 "temperature_2m": 16.1,
#                 "relative_humidity_2m": 85,
#                 "apparent_temperature": 15.4,
#                 "is_day": 0,
#                 "precipitation": 0.0,
#                 "rain": 0.0,
#                 "showers": 0.0,
#                 "snowfall": 0.0,
#                 "weather_code": 3,
#                 "cloud_cover": 100,
#                 "pressure_msl": 1009.4,
#                 "surface_pressure": 1005.5,
#                 "wind_speed_10m": 12.2,
#                 "wind_direction_10m": 214,
#                 "wind_gusts_10m": 24.5,
#             },
#             {
#                 "latitude": 48.85,
#                 "longitude": 2.3499994,
#                 "elevation": 33.0,
#                 "time": 1727067600,
#                 "temperature_2m": 15.7,
#                 "relative_humidity_2m": 90,
#                 "apparent_temperature": 15.5,
#                 "is_day": 0,
#                 "precipitation": 0.0,
#                 "rain": 0.0,
#                 "showers": 0.0,
#                 "snowfall": 0.0,
#                 "weather_code": 3,
#                 "cloud_cover": 100,
#                 "pressure_msl": 1009.5,
#                 "surface_pressure": 1005.6,
#                 "wind_speed_10m": 10.7,
#                 "wind_direction_10m": 192,
#                 "wind_gusts_10m": 26.6,
#             },
#             {
#                 "latitude": 48.85,
#                 "longitude": 2.3499994,
#                 "elevation": 33.0,
#                 "time": 1727071200,
#                 "temperature_2m": 15.8,
#                 "relative_humidity_2m": 87,
#                 "apparent_temperature": 15.3,
#                 "is_day": 1,
#                 "precipitation": 0.0,
#                 "rain": 0.0,
#                 "showers": 0.0,
#                 "snowfall": 0.0,
#                 "weather_code": 3,
#                 "cloud_cover": 100,
#                 "pressure_msl": 1009.9,
#                 "surface_pressure": 1006.0,
#                 "wind_speed_10m": 11.4,
#                 "wind_direction_10m": 191,
#                 "wind_gusts_10m": 27.4,
#             },
#             {
#                 "latitude": 48.85,
#                 "longitude": 2.3499994,
#                 "elevation": 33.0,
#                 "time": 1727074800,
#                 "temperature_2m": 15.5,
#                 "relative_humidity_2m": 88,
#                 "apparent_temperature": 15.1,
#                 "is_day": 1,
#                 "precipitation": 0.1,
#                 "rain": 0.1,
#                 "showers": 0.0,
#                 "snowfall": 0.0,
#                 "weather_code": 51,
#                 "cloud_cover": 67,
#                 "pressure_msl": 1009.9,
#                 "surface_pressure": 1006.0,
#                 "wind_speed_10m": 13.5,
#                 "wind_direction_10m": 209,
#                 "wind_gusts_10m": 32.0,
#             },
#             {
#                 "latitude": 48.85,
#                 "longitude": 2.3499994,
#                 "elevation": 33.0,
#                 "time": 1727078400,
#                 "temperature_2m": 15.9,
#                 "relative_humidity_2m": 84,
#                 "apparent_temperature": 15.4,
#                 "is_day": 1,
#                 "precipitation": 0.0,
#                 "rain": 0.0,
#                 "showers": 0.0,
#                 "snowfall": 0.0,
#                 "weather_code": 1,
#                 "cloud_cover": 34,
#                 "pressure_msl": 1010.1,
#                 "surface_pressure": 1006.2,
#                 "wind_speed_10m": 13.1,
#                 "wind_direction_10m": 212,
#                 "wind_gusts_10m": 27.7,
#             },
#             {
#                 "latitude": 48.85,
#                 "longitude": 2.3499994,
#                 "elevation": 33.0,
#                 "time": 1727082000,
#                 "temperature_2m": 16.5,
#                 "relative_humidity_2m": 77,
#                 "apparent_temperature": 15.4,
#                 "is_day": 1,
#                 "precipitation": 0.0,
#                 "rain": 0.0,
#                 "showers": 0.0,
#                 "snowfall": 0.0,
#                 "weather_code": 3,
#                 "cloud_cover": 100,
#                 "pressure_msl": 1010.3,
#                 "surface_pressure": 1006.4,
#                 "wind_speed_10m": 12.7,
#                 "wind_direction_10m": 209,
#                 "wind_gusts_10m": 28.4,
#             },
#             {
#                 "latitude": 48.85,
#                 "longitude": 2.3499994,
#                 "elevation": 33.0,
#                 "time": 1727085600,
#                 "temperature_2m": 17.4,
#                 "relative_humidity_2m": 73,
#                 "apparent_temperature": 16.2,
#                 "is_day": 1,
#                 "precipitation": 0.0,
#                 "rain": 0.0,
#                 "showers": 0.0,
#                 "snowfall": 0.0,
#                 "weather_code": 1,
#                 "cloud_cover": 27,
#                 "pressure_msl": 1009.8,
#                 "surface_pressure": 1005.9,
#                 "wind_speed_10m": 13.4,
#                 "wind_direction_10m": 216,
#                 "wind_gusts_10m": 27.0,
#             },
#             {
#                 "latitude": 48.85,
#                 "longitude": 2.3499994,
#                 "elevation": 33.0,
#                 "time": 1727089200,
#                 "temperature_2m": 18.3,
#                 "relative_humidity_2m": 68,
#                 "apparent_temperature": 17.1,
#                 "is_day": 1,
#                 "precipitation": 0.0,
#                 "rain": 0.0,
#                 "showers": 0.0,
#                 "snowfall": 0.0,
#                 "weather_code": 2,
#                 "cloud_cover": 50,
#                 "pressure_msl": 1009.6,
#                 "surface_pressure": 1005.7,
#                 "wind_speed_10m": 12.8,
#                 "wind_direction_10m": 218,
#                 "wind_gusts_10m": 28.4,
#             },
#             {
#                 "latitude": 48.85,
#                 "longitude": 2.3499994,
#                 "elevation": 33.0,
#                 "time": 1727092800,
#                 "temperature_2m": 19.0,
#                 "relative_humidity_2m": 65,
#                 "apparent_temperature": 18.3,
#                 "is_day": 1,
#                 "precipitation": 0.0,
#                 "rain": 0.0,
#                 "showers": 0.0,
#                 "snowfall": 0.0,
#                 "weather_code": 2,
#                 "cloud_cover": 77,
#                 "pressure_msl": 1009.0,
#                 "surface_pressure": 1005.1,
#                 "wind_speed_10m": 12.3,
#                 "wind_direction_10m": 212,
#                 "wind_gusts_10m": 29.5,
#             },
#             {
#                 "latitude": 48.85,
#                 "longitude": 2.3499994,
#                 "elevation": 33.0,
#                 "time": 1727096400,
#                 "temperature_2m": 19.4,
#                 "relative_humidity_2m": 59,
#                 "apparent_temperature": 18.4,
#                 "is_day": 1,
#                 "precipitation": 0.0,
#                 "rain": 0.0,
#                 "showers": 0.0,
#                 "snowfall": 0.0,
#                 "weather_code": 51,
#                 "cloud_cover": 77,
#                 "pressure_msl": 1008.9,
#                 "surface_pressure": 1005.0,
#                 "wind_speed_10m": 10.5,
#                 "wind_direction_10m": 202,
#                 "wind_gusts_10m": 37.8,
#             },
#             {
#                 "latitude": 48.85,
#                 "longitude": 2.3499994,
#                 "elevation": 33.0,
#                 "time": 1727100000,
#                 "temperature_2m": 18.4,
#                 "relative_humidity_2m": 71,
#                 "apparent_temperature": 18.2,
#                 "is_day": 1,
#                 "precipitation": 0.2,
#                 "rain": 0.2,
#                 "showers": 0.0,
#                 "snowfall": 0.0,
#                 "weather_code": 51,
#                 "cloud_cover": 100,
#                 "pressure_msl": 1008.2,
#                 "surface_pressure": 1004.3,
#                 "wind_speed_10m": 8.7,
#                 "wind_direction_10m": 187,
#                 "wind_gusts_10m": 26.6,
#             },
#             {
#                 "latitude": 48.85,
#                 "longitude": 2.3499994,
#                 "elevation": 33.0,
#                 "time": 1727103600,
#                 "temperature_2m": 16.9,
#                 "relative_humidity_2m": 82,
#                 "apparent_temperature": 18.3,
#                 "is_day": 1,
#                 "precipitation": 0.7,
#                 "rain": 0.7,
#                 "showers": 0.0,
#                 "snowfall": 0.0,
#                 "weather_code": 53,
#                 "cloud_cover": 100,
#                 "pressure_msl": 1007.5,
#                 "surface_pressure": 1003.6,
#                 "wind_speed_10m": 11.2,
#                 "wind_direction_10m": 186,
#                 "wind_gusts_10m": 34.6,
#             },
#             {
#                 "latitude": 48.85,
#                 "longitude": 2.3499994,
#                 "elevation": 33.0,
#                 "time": 1727107200,
#                 "temperature_2m": 17.9,
#                 "relative_humidity_2m": 75,
#                 "apparent_temperature": 17.0,
#                 "is_day": 1,
#                 "precipitation": 0.2,
#                 "rain": 0.2,
#                 "showers": 0.0,
#                 "snowfall": 0.0,
#                 "weather_code": 51,
#                 "cloud_cover": 100,
#                 "pressure_msl": 1007.7,
#                 "surface_pressure": 1003.8,
#                 "wind_speed_10m": 10.4,
#                 "wind_direction_10m": 182,
#                 "wind_gusts_10m": 23.4,
#             },
#             {
#                 "latitude": 48.85,
#                 "longitude": 2.3499994,
#                 "elevation": 33.0,
#                 "time": 1727110800,
#                 "temperature_2m": 17.8,
#                 "relative_humidity_2m": 79,
#                 "apparent_temperature": 17.1,
#                 "is_day": 1,
#                 "precipitation": 0.0,
#                 "rain": 0.0,
#                 "showers": 0.0,
#                 "snowfall": 0.0,
#                 "weather_code": 51,
#                 "cloud_cover": 100,
#                 "pressure_msl": 1006.8,
#                 "surface_pressure": 1002.9,
#                 "wind_speed_10m": 8.1,
#                 "wind_direction_10m": 193,
#                 "wind_gusts_10m": 22.7,
#             },
#             {
#                 "latitude": 48.85,
#                 "longitude": 2.3499994,
#                 "elevation": 33.0,
#                 "time": 1727114400,
#                 "temperature_2m": 16.8,
#                 "relative_humidity_2m": 80,
#                 "apparent_temperature": 15.9,
#                 "is_day": 0,
#                 "precipitation": 1.7,
#                 "rain": 1.7,
#                 "showers": 0.0,
#                 "snowfall": 0.0,
#                 "weather_code": 61,
#                 "cloud_cover": 100,
#                 "pressure_msl": 1007.0,
#                 "surface_pressure": 1003.1,
#                 "wind_speed_10m": 8.1,
#                 "wind_direction_10m": 201,
#                 "wind_gusts_10m": 24.1,
#             },
#             {
#                 "latitude": 48.85,
#                 "longitude": 2.3499994,
#                 "elevation": 33.0,
#                 "time": 1727118000,
#                 "temperature_2m": 16.2,
#                 "relative_humidity_2m": 78,
#                 "apparent_temperature": 14.8,
#                 "is_day": 0,
#                 "precipitation": 0.0,
#                 "rain": 0.0,
#                 "showers": 0.0,
#                 "snowfall": 0.0,
#                 "weather_code": 0,
#                 "cloud_cover": 1,
#                 "pressure_msl": 1006.8,
#                 "surface_pressure": 1002.9,
#                 "wind_speed_10m": 8.9,
#                 "wind_direction_10m": 201,
#                 "wind_gusts_10m": 19.8,
#             },
#             {
#                 "latitude": 48.85,
#                 "longitude": 2.3499994,
#                 "elevation": 33.0,
#                 "time": 1727121600,
#                 "temperature_2m": 15.5,
#                 "relative_humidity_2m": 83,
#                 "apparent_temperature": 13.9,
#                 "is_day": 0,
#                 "precipitation": 0.0,
#                 "rain": 0.0,
#                 "showers": 0.0,
#                 "snowfall": 0.0,
#                 "weather_code": 0,
#                 "cloud_cover": 11,
#                 "pressure_msl": 1006.8,
#                 "surface_pressure": 1002.9,
#                 "wind_speed_10m": 8.6,
#                 "wind_direction_10m": 180,
#                 "wind_gusts_10m": 23.0,
#             },
#             {
#                 "latitude": 48.85,
#                 "longitude": 2.3499994,
#                 "elevation": 33.0,
#                 "time": 1727125200,
#                 "temperature_2m": 15.0,
#                 "relative_humidity_2m": 86,
#                 "apparent_temperature": 14.1,
#                 "is_day": 0,
#                 "precipitation": 0.0,
#                 "rain": 0.0,
#                 "showers": 0.0,
#                 "snowfall": 0.0,
#                 "weather_code": 3,
#                 "cloud_cover": 100,
#                 "pressure_msl": 1006.9,
#                 "surface_pressure": 1003.0,
#                 "wind_speed_10m": 9.1,
#                 "wind_direction_10m": 189,
#                 "wind_gusts_10m": 23.8,
#             },
#             {
#                 "latitude": 48.85,
#                 "longitude": 2.3499994,
#                 "elevation": 33.0,
#                 "time": 1727128800,
#                 "temperature_2m": 14.9,
#                 "relative_humidity_2m": 89,
#                 "apparent_temperature": 14.1,
#                 "is_day": 0,
#                 "precipitation": 0.0,
#                 "rain": 0.0,
#                 "showers": 0.0,
#                 "snowfall": 0.0,
#                 "weather_code": 3,
#                 "cloud_cover": 100,
#                 "pressure_msl": 1006.5,
#                 "surface_pressure": 1002.6,
#                 "wind_speed_10m": 9.1,
#                 "wind_direction_10m": 198,
#                 "wind_gusts_10m": 25.9,
#             },
#             {
#                 "latitude": 48.85,
#                 "longitude": 2.3499994,
#                 "elevation": 33.0,
#                 "time": 1727132400,
#                 "temperature_2m": 15.0,
#                 "relative_humidity_2m": 90,
#                 "apparent_temperature": 14.6,
#                 "is_day": 0,
#                 "precipitation": 0.0,
#                 "rain": 0.0,
#                 "showers": 0.0,
#                 "snowfall": 0.0,
#                 "weather_code": 3,
#                 "cloud_cover": 99,
#                 "pressure_msl": 1006.7,
#                 "surface_pressure": 1002.8,
#                 "wind_speed_10m": 8.7,
#                 "wind_direction_10m": 204,
#                 "wind_gusts_10m": 24.1,
#             },
#         ]

#         weather_condition_list: WeatherConditions = (
#             historical_weather_condition_formatter(raw_data)
#         )

#         self.assertEqual(weather_condition_list, expected_output)


# if __name__ == "__main__":
#     unittest.main()
